name: Tests

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  workflow_dispatch:

jobs:
  integration-test:
    strategy:
      fail-fast: false
      matrix:
        ubuntu-versions:
          # Update whenever charmcraft.yaml is changed
          - series: jammy
            bases-index: 0
          - series: focal
            bases-index: 1
        tox-environments:
          - integration-db
          - integration-upgrade-1
          - integration-upgrade-2
          - integration-upgrade-3
          - integration-upgrade-4
          # To be enabled after data_interfaces v040
          # - integration-upgrade-5
          # - integration-upgrade-6
          # - integration-upgrade-7
          - integration-upgrade-databag
          - integration-s3
          - integration-opensearch
          - integration-kafka
        juju-version:
          - juju-bootstrap-option: "2.9.44"
            juju-snap-channel: "2.9/stable"
            libjuju-version: "2.9.49.0"
          - juju-bootstrap-option: "3.1.8"
            juju-snap-channel: "3.1/stable"
            libjuju-version: "3.2.2"
          - juju-bootstrap-option: "3.2.4"
            juju-snap-channel: "3.2/stable"
            libjuju-version: "3.2.3.0"
          - juju-bootstrap-option: "3.3.5"
            juju-snap-channel: "3.3/stable"
            libjuju-version: "3.3.1.1"
          - juju-bootstrap-option: "3.4.3"
            juju-snap-channel: "3.4/stable"
            libjuju-version: "3.4.0.0"
          - juju-bootstrap-option: "3.5.1"
            juju-snap-channel: "3.5/stable"
            libjuju-version: "3.5.0.0"
        exclude:
          - tox-environments: integration-upgrade-1
            juju-version: {juju-snap-channel: "2.9/stable"}
          - tox-environments: integration-upgrade-2
            juju-version: {juju-snap-channel: "2.9/stable"}
          - tox-environments: integration-upgrade-3
            juju-version: {juju-snap-channel: "2.9/stable"}
          - tox-environments: integration-upgrade-4
            juju-version: {juju-snap-channel: "2.9/stable"}
          - tox-environments: integration-upgrade-5
            juju-version: {juju-snap-channel: "2.9/stable"}
          - tox-environments: integration-upgrade-6
            juju-version: {juju-snap-channel: "2.9/stable"}
          - tox-environments: integration-upgrade-7
            juju-version: {juju-snap-channel: "2.9/stable"}
          - tox-environments: integration-upgrade-databag
            juju-version: {juju-snap-channel: "2.9/stable"}
          - tox-environments: integration-opensearch
            ubuntu-versions: {series: focal}
          - tox-environments: integration-kafka
            ubuntu-versions: {series: focal}
    name: ${{ matrix.tox-environments }} Juju ${{ matrix.juju-version.juju-snap-channel}} -- ${{ matrix.ubuntu-versions.series }}
    runs-on: ubuntu-latest
    timeout-minutes: 120
    steps:
      - name: Echo
        env:
          CI_PACKED_CHARMS: ${{ needs.build.outputs.charms }}
          LIBJUJU_VERSION_SPECIFIER: "==${{ matrix.juju-version.libjuju-version }}"
        id: select-tests
        run: |
          echo $LIBJUJU_VERSION_SPECIFIER
